spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/school_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:181204}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# JPA Auditing
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

server.port=8080
server.servlet.context-path=/

# Application Name
app.name=School Management System
app.version=1.0.0

# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET:your-super-secret-jwt-key-that-must-be-at-least-256-bits-long-for-hs512-algorithm-security-production}
app.jwt.expiration=36000
app.jwt.refresh.expiration=6048000

# Logging
logging.level.root=INFO
logging.level.com.school.school_management=DEBUG
logging.level.org.springframework.security=INFO

# Jackson
spring.jackson.serialization.indent_output=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.default-property-inclusion=non_null

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dhxec1unu}
cloudinary.api-key=${CLOUDINARY_API_KEY:227813845433369}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:p7bUbtwbmVfKMB_903bShqy1KK4}