name: Build Backend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push the backend Docker image
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./school-management
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/school-management-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/school-management-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/school-management-backend:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/school-management-backend:latest,mode=max
